import Link from "next/link";
import { ArrowRight, BrainCircuit, HeartPulse, Lightbulb, ShieldCheck } from "lucide-react";

const platforms=[
{name:"CareAxis",status:"Flagship platform",description:"Care operations and provider infrastructure designed for regulated care environments.",focus:"Healthcare, aged care, disability and community services",capabilities:["Scheduling and workforce coordination","Clinical documentation","Funding and billing infrastructure","Compliance and service governance"],href:"/platforms/careaxis",icon:HeartPulse},
{name:"Nexora AI",status:"In development",description:"Enterprise intelligence and automation capability for operational teams and decision-makers.",focus:"Enterprise operations and intelligent workflows",capabilities:["Decision-support infrastructure","Workflow automation","Knowledge orchestration","Responsible AI controls"],href:"/platforms/nexora-ai",icon:BrainCircuit},
{name:"Compliance Intelligence",status:"Platform capability",description:"Governance, evidence and assurance infrastructure for regulated organisations.",focus:"Compliance, audit, risk and assurance",capabilities:["Evidence management","Audit and review workflows","Issue and corrective-action tracking","Governance reporting"],href:"/platforms/compliance-intelligence",icon:ShieldCheck},
{name:"Future Ventures",status:"Incubation portfolio",description:"A controlled environment for emerging platforms, acquisitions and strategic technology ventures.",focus:"Emerging products and strategic opportunities",capabilities:["Product incubation","Technology acquisitions","Joint ventures","Market-entry partnerships"],href:"/platforms/future-ventures",icon:Lightbulb},
] as const;

export function InteractivePlatformGrid(){return <section id="portfolio" className="border-y border-[color:var(--border)] px-5 py-24"><div className="mx-auto max-w-7xl"><p className="eyebrow">Platform portfolio</p><h2 className="section-title max-w-4xl">Distinct products connected by a shared corporate operating model.</h2><div className="mt-14 grid gap-6 lg:grid-cols-2">{platforms.map(platform=>{const Icon=platform.icon;return <article key={platform.name} className="glass group rounded-[2rem] p-7 transition duration-300 hover:-translate-y-1 hover:border-indigo-400/30"><div className="flex items-start justify-between gap-6"><div className="grid size-12 place-items-center rounded-2xl bg-indigo-500/10 text-cyan-400"><Icon size={24} aria-hidden="true"/></div><span className="rounded-full border border-[color:var(--border)] px-3 py-1 text-xs font-bold text-[color:var(--muted)]">{platform.status}</span></div><h3 className="mt-9 text-3xl font-black tracking-[-0.04em]">{platform.name}</h3><p className="mt-5 max-w-2xl leading-7 text-[color:var(--muted)]">{platform.description}</p><div className="mt-7 rounded-2xl border border-[color:var(--border)] p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-indigo-400">Primary focus</p><p className="mt-3 font-semibold">{platform.focus}</p></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{platform.capabilities.map(capability=><div key={capability} className="rounded-2xl bg-[color:var(--background)] px-4 py-3 text-sm font-semibold">{capability}</div>)}</div><Link href={platform.href} className="mt-8 inline-flex items-center gap-2 font-bold text-cyan-400 transition hover:text-cyan-300">Explore {platform.name}<ArrowRight size={17} aria-hidden="true" className="transition group-hover:translate-x-1"/></Link></article>})}</div></div></section>}
